# Generated by Django 3.0.5 on 2020-04-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Hersteller', models.CharField(max_length=50)),
                ('Grafikprozessor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mainboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modell', models.CharField(max_length=50)),
                ('Sockel', models.CharField(max_length=20)),
                ('Chipsatz', models.CharField(max_length=20)),
                ('Formfaktor', models.CharField(max_length=20)),
                ('RAM_Typ', models.CharField(max_length=20)),
                ('RAM_Bauform', models.CharField(max_length=20)),
                ('RAM_Architektur', models.CharField(max_length=20)),
                ('RAM_Einzelmodul', models.IntegerField(default=0)),
                ('BIOS', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prozessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serie', models.CharField(max_length=50)),
                ('Modell', models.CharField(max_length=50)),
                ('Codename', models.CharField(max_length=50)),
                ('Kerne', models.IntegerField(default=0)),
                ('Threads', models.IntegerField(default=0)),
                ('Prozessortakt', models.FloatField(default=0.0)),
                ('Turbotakt', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modellname', models.CharField(max_length=50)),
                ('Gesamtkapazitaet', models.IntegerField(default=0)),
                ('Modulanzahl', models.IntegerField(default=0)),
                ('Speicherart', models.CharField(max_length=30)),
                ('Speichertyp', models.CharField(max_length=20)),
                ('Bauform', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hersteller', models.CharField(max_length=50)),
                ('Modellserie', models.CharField(max_length=50)),
                ('Kapazität', models.IntegerField(default=0)),
                ('Lesegeschw', models.IntegerField(default=0)),
                ('Schreibgeschw', models.IntegerField(default=0)),
            ],
        ),
    ]
